# {% set name = "click" %}
# {% set version = "7.0" %}

package:
  name: prototype
  version: 1.0.0

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7
  path: . .

# build:
#   number: 0
#   script: python -m pip install . -vv

requirements:
  # host:
  #   - pip
  #   - python
  #   - setuptools
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - prototype

test:
  imports:
    - prototype

about:
  home: https://github.com/bcc2761/FRE-CLI-Prototype
  # license: BSD
  # license_family: BSD
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang
